name: frontend ci/cd

on:
  push:
    branches: [staging, main]

jobs:
  verify-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: install dependencies
        run: npm ci

      - name: lint check
        run: npm run lint

      - name: test
        run: npm run test

      - name: build
        env:
          NEXT_PUBLIC_API_URL: ${{secrets.NEXT_PUBLIC_API_URL}}
          INTERNAL_API_URL: ${{secrets.NEXT_PUBLIC_API_URL}}
        run: npm run build

      # - name: List .next contents (debug)
      #   run: |
      #     echo "Contents of .next:"
      #     ls -la .next/ || echo ".next folder doesn't exist"
      #     echo "Contents of .next/standalone (if it exists):"
      #     ls -la .next/standalone/ 2>/dev/null || echo "standalone folder missing"
      #     echo "Contents of .next/static (if it exists):"
      #     ls -la .next/static/ 2>/dev/null || echo "static folder missing"

      - name: upload build output
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            .next/standalone
            .next/static
            public
          retention-days: 1

  docker-build-push:
    needs: verify-and-build
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v4

      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: .

      - name: login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build docker image and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ak0384221/yourstore-frontend-public:${{github.ref_name}}

  # deploy-to-render:
  #   needs: docker-build-push
  #   runs-on: ubuntu-terests
  #   if: github.ref == 'refs/heads/main'
  #   steps:
  #     - name: deploy to render
  #       run: curl -X POST ""
