name: frontend ci/cd

on:
  push:
    branches: [staging, main]

jobs:
  verify-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v4

      - name: setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 11.24.0

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: install dependencies
        run: pnpm install --frozen-lockfile

      - name: lint check
        run: pnpm run lint

      - name: test
        run: pnpm run test

      - name: build
        env:
          NEXT_PUBLIC_API_URL: ${{secrets.NEXT_PUBLIC_API_URL}}
          INTERNAL_API_URL: ${{secrets.NEXT_PUBLIC_API_URL}}
        run: pnpm run build

      - name: upload build output
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            .next/standalone
            .next/static
            public
          retention-days: 1

  docker-build-push:
    needs: verify-and-build
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v4

      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: .

      - name: login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build docker image and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ak0384221/yourstore-frontend-public:${{github.ref_name}}

  # deploy-to-render:
  #   needs: docker-build-push
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main'
  #   steps:
  #     - name: deploy to render
  #       run: curl -X POST ""
